[package]
name = "trac"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
trees = "0.4.2"
ndarray = "0.14.0"
mnist = "0.5.0"
chrono = "0.4.24"
backtrace-on-stack-overflow = "0.3.0"

